version: 2
updates:
  # Automatic upgrade for Go modules.
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # Automatic upgrade for Go modules in examples/cmd/snapshotting
  - package-ecosystem: "gomod"
    directory: "/examples/cmd/snapshotting"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/firecracker-microvm/firecracker-go-sdk"

  # Automatic upgrade for GitHub Actions packages.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
