# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
# 	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

steps:
  - label: ':ec2: environment'
    command:
      - uname -a
      - go version

  - label: ':go: go mod download'
    command: 'go mod download'
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - label: ':linux: setup taps'
    commands:
      - 'sudo ip tuntap add fc-test-tap${BUILDKITE_BUILD_NUMBER} mode tap user $(sudo id -u buildkite-agent)'
      - 'sudo ip tuntap add fc-root-tap${BUILDKITE_BUILD_NUMBER} mode tap user $(sudo id -u buildkite-agent)'
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  # We use a "wait" step here, because Go's module logic freaks out when
  # multiple go builds are downloading to the same cache.
  - wait

  - label: 'git log validation'
    command: './.buildkite/logcheck.sh'

  - label: 'build'
    commands:
      - 'make'
      - 'make -C cni'
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - label: ':hammer: tests'
    commands:
      - 'ln -s /var/lib/fc-ci/vmlinux.bin testdata/vmlinux'
      - 'ln -s /var/lib/fc-ci/rootfs.ext4 testdata/root-drive.img'
      - 'ln -s /usr/local/bin/firecracker-v0.18.0 testdata/firecracker'
      - 'ln -s /usr/local/bin/jailer-v0.18.0 testdata/jailer'
      - "DISABLE_ROOT_TESTS=true FC_TEST_TAP=fc-test-tap${BUILDKITE_BUILD_NUMBER} make test EXTRAGOARGS='-v -count=1'"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - label: ':hammer: root tests'
    commands:
      - 'ln -s /var/lib/fc-ci/vmlinux.bin testdata/vmlinux'
      - 'ln -s /var/lib/fc-ci/rootfs.ext4 testdata/root-drive.img'
      - 'cp /usr/local/bin/firecracker-v0.18.0 testdata/firecracker'
      - 'cp /usr/local/bin/jailer-v0.18.0 testdata/jailer'
      - 'make -C cni install CNI_BIN_ROOT=$(pwd)/testdata/bin'
      - "sudo FC_TEST_TAP=fc-root-tap${BUILDKITE_BUILD_NUMBER} make test EXTRAGOARGS='-v -count=1'"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  # This allows the cleanup step to always run, regardless of test failure
  - wait: ~
    continue_on_failure: true

  - label: ':linux: cleanup taps'
    commands:
      - 'sudo ip tuntap del fc-test-tap${BUILDKITE_BUILD_NUMBER} mode tap'
      - 'sudo ip tuntap del fc-root-tap${BUILDKITE_BUILD_NUMBER} mode tap'
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

