// Code generated by go-swagger; DO NOT EDIT.

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
// 	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/firecracker-microvm/firecracker-go-sdk/client/models"
)

// PutEntropyDeviceReader is a Reader for the PutEntropyDevice structure.
type PutEntropyDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutEntropyDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPutEntropyDeviceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutEntropyDeviceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutEntropyDeviceNoContent creates a PutEntropyDeviceNoContent with default headers values
func NewPutEntropyDeviceNoContent() *PutEntropyDeviceNoContent {
	return &PutEntropyDeviceNoContent{}
}

/*PutEntropyDeviceNoContent handles this case with default header values.

Entropy device created
*/
type PutEntropyDeviceNoContent struct {
}

func (o *PutEntropyDeviceNoContent) Error() string {
	return fmt.Sprintf("[PUT /entropy][%d] putEntropyDeviceNoContent ", 204)
}

func (o *PutEntropyDeviceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutEntropyDeviceDefault creates a PutEntropyDeviceDefault with default headers values
func NewPutEntropyDeviceDefault(code int) *PutEntropyDeviceDefault {
	return &PutEntropyDeviceDefault{
		_statusCode: code,
	}
}

/*PutEntropyDeviceDefault handles this case with default header values.

Internal server error
*/
type PutEntropyDeviceDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the put entropy device default response
func (o *PutEntropyDeviceDefault) Code() int {
	return o._statusCode
}

func (o *PutEntropyDeviceDefault) Error() string {
	return fmt.Sprintf("[PUT /entropy][%d] putEntropyDevice default  %+v", o._statusCode, o.Payload)
}

func (o *PutEntropyDeviceDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutEntropyDeviceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
